# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.cliente import Cliente  # noqa: F401,E501
from swagger_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, clientes: List[Cliente]=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param clientes: The clientes of this InlineResponse200.  # noqa: E501
        :type clientes: List[Cliente]
        """
        self.swagger_types = {
            'clientes': List[Cliente]
        }

        self.attribute_map = {
            'clientes': 'clientes'
        }
        self._clientes = clientes

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def clientes(self) -> List[Cliente]:
        """Gets the clientes of this InlineResponse200.

        array de clientes  # noqa: E501

        :return: The clientes of this InlineResponse200.
        :rtype: List[Cliente]
        """
        return self._clientes

    @clientes.setter
    def clientes(self, clientes: List[Cliente]):
        """Sets the clientes of this InlineResponse200.

        array de clientes  # noqa: E501

        :param clientes: The clientes of this InlineResponse200.
        :type clientes: List[Cliente]
        """

        self._clientes = clientes
